" Where to look to load configs
set runtimepath^=$XDG_CONFIG_HOME/vim
set runtimepath+=$XDG_DATA_HOME/vim
set runtimepath+=$XDG_CONFIG_HOME/vim/after
set runtimepath+=$XDG_DATA_HOME/vim/after
set runtimepath+=$VIM
set runtimepath+=$VIMRUNTIME

if v:version > 704
	" Where to look to load packages
	set packpath^=$XDG_DATA_HOME/vim,$XDG_CONFIG_HOME/vim
	set packpath=+$XDG_CONFIG_HOME/vim/after,$XDG_DATA_HOME/vim/after
endif

" Where to look for netrw bookmarks/spellfiles/etc.
let g:netrw_home = $XDG_DATA_HOME."/vim"
let s:spelldir=$XDG_DATA_HOME."/vim/spell"
if !isdirectory($spelldir)
	call mkdir($spelldir, 'p', 0755)
endif
set viewdir=$XDG_DATA_HOME/vim/view
if !isdirectory($viewdir)
	call mkdir($viewdir, 'p', 0755)
endif

" Where to look for .bak, .swp, and undofiles
set backupdir=$XDG_CACHE_HOME/vim/backup
if !isdirectory(&backupdir)
	call mkdir(&backupdir, 'p', 0755)
endif
set directory=$XDG_CACHE_HOME/vim/swap
if !isdirectory(&directory)
	call mkdir(&directory, 'p', 0755)
endif
set undodir=$XDG_CACHE_HOME/vim/undo
if !isdirectory(&undodir)
	call mkdir(&undodir, 'p', 0755)
endif

" Set viminfo state
set viminfo=%,<800,'10,/50,:100,h,f0,n$XDG_CACHE_HOME/vim/viminfo
"           | |    |   |   |    | |  + viminfo file path
"           | |    |   |   |    | + file marks 0-9,A-Z 0=NOT stored
"           | |    |   |   |    + disable 'hlsearch' loading viminfo
"           | |    |   |   + command-line history saved
"           | |    |   + search history saved
"           | |    + files marks saved
"           | + lines saved each register (old name for <,vi6.2)
"           + save/restore buffer list

let g:general_settings_file = expand($XDG_CONFIG_HOME) . '/nvim/settings.vim'
execute 'source '.general_settings_file
